apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 5m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: mariadb-operator
  targetNamespace: mariadb-operator
  resources:
    - mariadb-operator.yaml
