apiVersion: v1
kind: Service
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  ports:
    - port: 8085
      targetPort: 8080
  selector:
    app: mariadb-operator
  type: ClusterIP
