---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: mariadb-namespace
#   namespace: flux-system
# spec:
#   interval: 5m0s
#   path: ./apps/mariadb-operator
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: infra
#   resources:
#   - mariadb-operator-namespace.yaml



# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: mariadb-operator
#   namespace: flux-system
# spec:
#   interval: 5m0s
#   path: ./apps/mariadb-operator
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: infra
#   dependsOn:
#     - name: mariadb-namespace  # Ensures namespace is created first
#   targetNamespace: mariadb-operator



#   ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: mariadb-ha
#   namespace: flux-system
# spec:
#   interval: 5m0s
#   path: ./apps/mariadb-ha
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: mariadb-ha
#   targetNamespace: mariadb-ha
