---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-mariadb
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/test-mariadb
  prune: true
  sourceRef:
    kind: GitRepository
    name: test
