apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-multi-certs
  namespace: kube-system
spec:
  secretName: hubble-multi-certs
  duration: 8760h # 1 year
  renewBefore: 720h # renew 30d before expiry
  issuerRef:
    name: hubble-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    # - "*.kube-system.svc.cluster.local"
    - "hubble-peer.default.hubble-grpc.cilium.io"
    - "hubble-relay.kube-system.svc.cluster.local"
    - "minikube.default.hubble-grpc.cilium.io"
  usages:
    - server auth
    - client auth


# Test Certificate with short duration and multiple domains

# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: hubble-multi-certs
#   namespace: kube-system
# spec:
#   secretName: hubble-multi-certs
#   duration: 1h        
#   renewBefore: 5m     
#   issuerRef:
#     name: hubble-ca-issuer
#     kind: ClusterIssuer
#   dnsNames:
#     - "hubble-peer.default.hubble-grpc.cilium.io"
#     - "hubble-relay.kube-system.svc.cluster.local"
#     - "minikube.default.hubble-grpc.cilium.io"
#   usages:
#     - server auth
#     - client auth
