apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      initContainers:
        - name: install-s3-plugin
          image: fluent/fluentd:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache --update --virtual .build-deps \
                sudo build-base ruby-dev libffi-dev \
              && gem install fluent-plugin-s3 --no-document \
              && apk del .build-deps \
              && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem
          volumeMounts:
            - name: fluentd-plugins
              mountPath: /fluentd/plugins
      containers:
        - name: fluentd
          image: fluent/fluentd:latest
          ports:
            - containerPort: 24224
          env:
            - name: FLUENTD_OPT
              value: "-p /fluentd/plugins"
          volumeMounts:
            - name: config
              mountPath: /fluentd/etc
            - name: fluentd-plugins
              mountPath: /fluentd/plugins
      volumes:
        - name: config
          configMap:
            name: fluentd-config
        - name: fluentd-plugins
          emptyDir: {}
