apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      securityContext:
        runAsUser: 0  # run as root
      initContainers:
        - name: install-s3-plugin
          image: fluent/fluentd:v1.16-1
          command: ["/bin/sh", "-c"]
          args:
            - |
              gem install fluent-plugin-s3 --no-document
          volumeMounts:
            - name: fluentd-plugins
              mountPath: /fluentd/plugins
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.16-1
          env:
            - name: FLUENTD_OPT
              value: "-p /fluentd/plugins"
          ports:
            - containerPort: 24224
          volumeMounts:
            - name: config
              mountPath: /fluentd/etc
            - name: fluentd-plugins
              mountPath: /fluentd/plugins
      volumes:
        - name: config
          configMap:
            name: fluentd-config
        - name: fluentd-plugins
          emptyDir: {}
