namespace: script-runner  # Ensure this line is here if your resources are to be in the flux-system namespace

configMapGenerator:
  - name: logging-script-config
    files:
      - logging-script.sh  # Automatically create a ConfigMap from the shell script

resources:
  - namespace.yaml
  - logging-deployment.yaml  # Referencing the deployment that uses the ConfigMap
