apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - namespace.yaml
  - fluent-bit-configmap.yaml
  - fluent-bit-daemonset.yaml
  - fluentd-configmap.yaml
  - fluentd-deployment.yaml
  - fluentd-service.yaml
  - s3-cleanup-configmap.yaml
  # - s3-cleanup-cron-job.yaml
  - pv-pvc.yaml
