apiVersion: v1
kind: PersistentVolume
metadata:
  name: boto3-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/boto3  # Make sure this path exists on your node (Minikube or host)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boto3-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
