apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-cleanup-script
  namespace: logging
data:
  delete_old_s3_objects.py: |
    for i in range(1, 100):
        #add delay of 3 seconds
        import time
        time.sleep(3)
        print(f"Deleting old S3 objects {i}")
