apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-cleaner
  namespace: logging
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: boto3-layer
              persistentVolumeClaim:
                claimName: boto3-pvc
            - name: script
              configMap:
                name: s3-cleanup-script
          containers:
            - name: s3-cleaner
              image: python:3.10-slim
              command: ["/bin/sh", "-c"]
              args:
                - |
                  if [ ! -d "/boto3/boto3_installed" ]; then
                    pip install boto3 -t /boto3 && touch /boto3/boto3_installed;
                  fi && \
                  export PYTHONPATH=$PYTHONPATH:/boto3 && \
                  python /scripts/delete_old_s3_objects.py
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-creds
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-creds
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_DEFAULT_REGION
                  value: us-east-1
              volumeMounts:
                - name: boto3-layer
                  mountPath: /boto3
                - name: script
                  mountPath: /scripts
